### ISSUE TITLE
Color element not supported

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#73]
Apparently, color elements are not yet supported.

Windows 10 PC

**Comment by hoffe86** [comment]
@cd-tronic Have you an option to test my change?
Currently I have no device, which needs a color picker

You will find the code in features/color-element branch

**Comment by cd-tronic** [comment]
@hoffe86 ,
give me some time and i will setup something. I've got DMX and LED Lights flying around but currenty not integrated in OpenHAB. But i thought about integrating them last week :D

**Comment by hoffe86** [comment]
@cd-tronic 
Take your time in the meanwhile I will take care on #76 and #94

**Comment by cd-tronic** [comment]
okay. sorry that i can't help you more at the moment. I just don't have time for this... or brain after several hours of programming every day at the moment.

**Comment by hoffe86** [comment]
No worry, I have also not so much time

**Comment by cd-tronic** [comment]
![image](https://user-images.githubusercontent.com/7304760/107117570-836a9b00-687b-11eb-9bdc-fafa06645fbe.png)

hi @hoffe86,
I get this message as soon as i try to change the color. I try to find the root cause of this.

**Comment by cd-tronic** [comment]
Ah ok. The problem is that it is not really HSV. 
The X value goes from 0 to 360 (degree on the circle).
Y from 0 to 100 
Z also from 0 to 100

I need to leav now for the moment but will look at it later again.

**Comment by cd-tronic** [comment]
Hi @hoffe86 
can you please check PR #187 
This is my first idea of doing it. I had a bit to try out to get it working.
Currently it's only OneWay (from App to OH) but i will add the other direction later.

I'm transmitting an PR before because we might need to change the Colorpallet but i don't exactly undersand how you did this.
It would be easier to have the colorfield in the same way it is in the Android App cause this is the way the calculated angle is ok. 
Red on the right, Green on the Bottom, Light Blue on the left and purple on the top. I will post an screenshot from my phone asap.
Also we need to take White in the middle and add an slider for the brightness. I think there is no chance to do this in a nother way because if we leave it with black in the middle it won't be possible to get a white color (i think).
Any opinion on this?

Regards,

**Comment by cd-tronic** [comment]
![Screenshot_20210206-205821~2.png](https://user-images.githubusercontent.com/7304760/107128466-35c35200-68be-11eb-8ec1-1b9b0b71d9be.png)

**Comment by hoffe86** [comment]
@cd-tronic Feel free to change the control as needed.
Maybe you can also have a look on the UWP default color picker if this would simplify the implementation?
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/color-picker

I tested the control in the [XAML Control Library](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab) app and seems it has the similar functionality like the control in the android app.
